import { Helmet } from "react-helmet";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Disclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Disclaimer - Name Finder</title>
        <meta name="description" content="Read Name Finder's disclaimer regarding the use of our name generation tool and generated content." />
        <link rel="canonical" href="https://namefinder-nu.vercel.app/disclaimer" />
      </Helmet>

      <div className="min-h-screen flex flex-col">
        <Header />
        
        <main className="flex-1 py-16 px-4">
          <div className="container mx-auto max-w-4xl">
            <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
            <p className="text-muted-foreground mb-8">
              <strong>Last Updated:</strong> January 1, 2025
            </p>

            <div className="prose prose-slate max-w-none space-y-8">
              <section>
                <h2 className="text-2xl font-semibold mb-4">1. General Information</h2>
                <p className="text-muted-foreground mb-4">
                  The information provided by Name Finder ("we," "us," or "our") on namefinder-nu.vercel.app (the "Site") is for general informational purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.
                </p>
                <p className="text-muted-foreground">
                  Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Site or reliance on any information provided on the Site. Your use of the Site and your reliance on any information on the Site is solely at your own risk.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">2. No Guarantee of Name Availability</h2>
                <p className="text-muted-foreground mb-4">
                  Name Finder generates name suggestions using AI algorithms. We do not guarantee that any generated name is:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Available as a business name, domain name, or trademark</li>
                  <li>Free from trademark or copyright conflicts</li>
                  <li>Suitable for your specific business or purpose</li>
                  <li>Compliant with naming regulations in your jurisdiction</li>
                  <li>Free from negative connotations in any language or culture</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">3. Trademark and Legal Research</h2>
                <p className="text-muted-foreground mb-4">
                  You are solely responsible for conducting comprehensive trademark searches, domain availability checks, and legal research before using any name generated by our tool for commercial purposes.
                </p>
                <p className="text-muted-foreground mb-4">
                  We strongly recommend consulting with a trademark attorney before making any final decisions about business naming and branding. Name Finder does not provide legal advice and should not be relied upon as a substitute for professional legal consultation.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">4. No Professional Advice</h2>
                <p className="text-muted-foreground mb-4">
                  The Site and its content are not intended to be professional advice. Always seek the advice of qualified professionals with any questions you may have regarding:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Trademark registration and intellectual property law</li>
                  <li>Business naming strategies and branding</li>
                  <li>Domain registration and website development</li>
                  <li>Marketing and business strategy</li>
                  <li>Tax implications of business naming</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">5. External Links Disclaimer</h2>
                <p className="text-muted-foreground mb-4">
                  The Site may contain links to external websites (including domain registrars) that are not provided or maintained by or in any way affiliated with Name Finder.
                </p>
                <p className="text-muted-foreground mb-4">
                  Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. We are not responsible for the content, privacy practices, or terms of service of any linked sites.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">6. Affiliate Links Disclosure</h2>
                <p className="text-muted-foreground mb-4">
                  Name Finder participates in affiliate programs with domain registrars and other service providers. When you click on affiliate links and make a purchase, we may receive a commission at no additional cost to you.
                </p>
                <p className="text-muted-foreground mb-4">
                  Our affiliate partnerships do not influence the names generated by our tool. We recommend domain registrars based on their reputation and service quality, not solely on affiliate commissions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">7. Errors and Omissions</h2>
                <p className="text-muted-foreground mb-4">
                  While we strive to provide accurate and up-to-date information, the Site may contain technical inaccuracies, typographical errors, or other mistakes. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update information at any time without prior notice.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">8. Service Availability</h2>
                <p className="text-muted-foreground mb-4">
                  We do not guarantee that the Site will be available at all times or that it will be free from errors, viruses, or other harmful components. We may suspend, withdraw, or restrict the availability of all or any part of the Site for business and operational reasons.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">9. Third-Party Advertisements</h2>
                <p className="text-muted-foreground mb-4">
                  We display third-party advertisements through Google AdSense. We do not endorse, control, or assume responsibility for any advertisements displayed on the Site. The presence of advertisements does not imply our endorsement of the advertised products or services.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">10. User-Generated Content</h2>
                <p className="text-muted-foreground mb-4">
                  If users provide any content, feedback, or suggestions through our Site, we are not responsible for the accuracy, usefulness, or legality of such content. User opinions do not reflect the views of Name Finder.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">11. Changes to This Disclaimer</h2>
                <p className="text-muted-foreground mb-4">
                  We may update this Disclaimer from time to time. Any changes will be posted on this page with an updated "Last Updated" date. Your continued use of the Site after any changes constitutes acceptance of the updated Disclaimer.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">12. Jurisdiction-Specific Information</h2>
                <p className="text-muted-foreground mb-4">
                  Business naming laws, trademark regulations, and domain registration policies vary by jurisdiction. Information and suggestions provided by Name Finder may not be applicable or compliant with the laws of your specific location.
                </p>
                <p className="text-muted-foreground">
                  Always consult with local legal and business professionals to ensure compliance with applicable laws and regulations in your jurisdiction.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">13. Contact Us</h2>
                <p className="text-muted-foreground mb-4">
                  If you have any questions or concerns about this Disclaimer, please contact us:
                </p>
                <ul className="list-none space-y-2 text-muted-foreground">
                  <li>Email: contact@namefinder.com</li>
                  <li>Website: <a href="https://namefinder-nu.vercel.app" className="text-primary hover:underline">namefinder-nu.vercel.app</a></li>
                </ul>
              </section>

              <div className="bg-accent/20 rounded-xl p-6 mt-8">
                <p className="text-muted-foreground text-sm">
                  <strong>Important Notice:</strong> By using Name Finder, you acknowledge that you have read, understood, and agreed to this Disclaimer. You accept full responsibility for your use of any names generated by our tool and agree to conduct appropriate due diligence before using any name commercially.
                </p>
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Disclaimer;
