import { Helmet } from "react-helmet";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqData = [
    {
      question: "How does Name Finder generate business names?",
      answer: "Name Finder uses advanced AI algorithms combined with linguistic patterns and industry-specific knowledge to generate creative, brandable names. Our system analyzes your keywords, understands context, and creates unique combinations that are memorable and meaningful for your specific niche."
    },
    {
      question: "Is Name Finder really free to use?",
      answer: "Yes! Name Finder is completely free to use. You can generate unlimited name ideas without any cost. We earn revenue through affiliate partnerships with domain registrars when you check domain availability, which allows us to keep the tool free for everyone."
    },
    {
      question: "How do I check if a domain name is available?",
      answer: "Each generated name includes a 'Check Domain Availability' button that takes you directly to our partner domain registrar where you can check if the .com domain is available. You can also search for other domain extensions like .net, .io, .co, and more."
    },
    {
      question: "Can I use the generated names for my business?",
      answer: "Yes! All names generated by Name Finder are free to use for your business, brand, or project. However, we recommend checking for trademark conflicts and ensuring the domain and social media handles are available before finalizing your choice."
    },
    {
      question: "What types of businesses can use Name Finder?",
      answer: "Name Finder works for all types of businesses and projects including startups, e-commerce stores, YouTube channels, podcasts, gaming channels, fashion brands, tech companies, SaaS products, and more. We have category-specific algorithms for different industries."
    },
    {
      question: "How many name ideas will I get?",
      answer: "Each generation produces 10 unique name suggestions based on your keywords and selected category. You can generate new names as many times as you want to explore different options and find the perfect fit for your brand."
    },
    {
      question: "What makes a good business name?",
      answer: "A good business name is memorable, easy to spell and pronounce, unique, relevant to your industry, and has an available domain. It should be short (ideally 1-3 words), avoid numbers and hyphens, and convey something about your brand's personality or values."
    },
    {
      question: "Can I save my favorite names?",
      answer: "Yes! Click the heart icon on any generated name to add it to your favorites list. Your favorites are automatically saved in your browser, so you can come back later to review and compare your top choices."
    },
    {
      question: "What if I need help choosing between names?",
      answer: "Consider these factors: domain availability, ease of spelling and pronunciation, trademark availability, how well it represents your brand, and feedback from potential customers. You can also check our blog for detailed guides on choosing the perfect business name."
    },
    {
      question: "Do you offer trademark checking services?",
      answer: "While Name Finder doesn't directly check trademarks, we recommend using the USPTO trademark database (for US businesses) or your country's trademark office to ensure your chosen name isn't already trademarked in your industry."
    },
    {
      question: "Can I suggest new features or categories?",
      answer: "Absolutely! We love hearing from our users. Contact us through our contact page with your suggestions, and we'll consider them for future updates. User feedback helps us make Name Finder better for everyone."
    },
    {
      question: "Is my search data private?",
      answer: "Yes, we respect your privacy. Your searches and generated names are not stored on our servers or shared with third parties. The only data we store locally is your favorites list (in your browser). Read our Privacy Policy for complete details."
    }
  ];

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqData.map(faq => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer
      }
    }))
  };

  return (
    <>
      <Helmet>
        <title>FAQ - Name Finder | Frequently Asked Questions</title>
        <meta name="description" content="Find answers to common questions about Name Finder, business naming, domain availability, and how to use our AI-powered name generator tool effectively." />
        <meta name="keywords" content="name finder faq, business naming questions, domain availability help, brand naming guide, startup naming tips" />
        <link rel="canonical" href="https://namefinder-nu.vercel.app/faq" />
        <meta property="og:title" content="FAQ - Name Finder | Frequently Asked Questions" />
        <meta property="og:description" content="Find answers to common questions about Name Finder and business naming." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://namefinder-nu.vercel.app/faq" />
        <script type="application/ld+json">
          {JSON.stringify(structuredData)}
        </script>
      </Helmet>

      <div className="min-h-screen flex flex-col">
        <Header />
        
        <main className="flex-1 py-16 px-4">
          <div className="container mx-auto max-w-4xl">
            <div className="text-center mb-12">
              <h1 className="text-4xl md:text-5xl font-bold mb-4">
                Frequently Asked Questions
              </h1>
              <p className="text-lg text-muted-foreground">
                Everything you need to know about Name Finder and business naming
              </p>
            </div>

            <div className="bg-card rounded-xl shadow-lg p-8">
              <Accordion type="single" collapsible className="w-full">
                {faqData.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>

            <div className="mt-12 bg-accent/20 rounded-xl p-8 text-center">
              <h2 className="text-2xl font-bold mb-4">Still Have Questions?</h2>
              <p className="text-muted-foreground mb-6">
                Can't find what you're looking for? Contact our team and we'll be happy to help.
              </p>
              <a
                href="/contact"
                className="inline-block bg-primary text-primary-foreground px-8 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors"
              >
                Contact Us
              </a>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default FAQ;
