import { Helmet } from "react-helmet";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <>
      <Helmet>
        <title>Terms & Conditions - Name Finder</title>
        <meta name="description" content="Read the terms and conditions for using Name Finder's business name generator tool." />
        <link rel="canonical" href="https://namefinder-nu.vercel.app/terms" />
      </Helmet>

      <div className="min-h-screen flex flex-col">
        <Header />
        
        <main className="flex-1 py-16 px-4">
          <div className="container mx-auto max-w-4xl">
            <h1 className="text-4xl font-bold mb-8">Terms & Conditions</h1>
            <p className="text-muted-foreground mb-8">
              <strong>Effective Date:</strong> January 1, 2025
            </p>

            <div className="prose prose-slate max-w-none space-y-8">
              <section>
                <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
                <p className="text-muted-foreground mb-4">
                  Welcome to Name Finder. By accessing and using our website namefinder-nu.vercel.app (the "Site"), you accept and agree to be bound by the terms and provision of this agreement.
                </p>
                <p className="text-muted-foreground">
                  If you do not agree to these Terms & Conditions, please do not use our Site.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
                <p className="text-muted-foreground mb-4">
                  Name Finder provides an AI-powered name generation tool that helps users discover creative and unique names for businesses, startups, YouTube channels, games, podcasts, and other creative projects.
                </p>
                <p className="text-muted-foreground">
                  Our service is provided free of charge and includes features such as name generation, favorite name storage, and domain availability checking through affiliate partnerships.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">3. User Responsibilities</h2>
                <p className="text-muted-foreground mb-4">
                  By using our Site, you agree to:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Use the service for lawful purposes only</li>
                  <li>Not use the service to generate names that infringe on existing trademarks or copyrights</li>
                  <li>Not attempt to disrupt or interfere with the Site's functionality</li>
                  <li>Not use automated tools or bots to access the Site excessively</li>
                  <li>Conduct your own trademark and copyright research before using any generated names commercially</li>
                  <li>Not hold Name Finder liable for any trademark or copyright disputes arising from your use of generated names</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">4. Intellectual Property</h2>
                <p className="text-muted-foreground mb-4">
                  The Site and its original content, features, and functionality are owned by Name Finder and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
                </p>
                <p className="text-muted-foreground mb-4">
                  <strong>Generated Names:</strong> Names generated by our tool are provided as suggestions. We make no claim to ownership or exclusive rights to any generated names. You are free to use generated names commercially, but you are solely responsible for:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Conducting trademark searches before commercial use</li>
                  <li>Ensuring the name does not infringe on existing intellectual property</li>
                  <li>Obtaining necessary trademark registrations</li>
                  <li>Any legal consequences arising from your use of a generated name</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">5. Disclaimer of Warranties</h2>
                <p className="text-muted-foreground mb-4">
                  The Site is provided on an "AS IS" and "AS AVAILABLE" basis. Name Finder makes no warranties, expressed or implied, and hereby disclaims all warranties including, without limitation:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground mb-4">
                  <li>Warranties of merchantability or fitness for a particular purpose</li>
                  <li>Warranties that the service will be uninterrupted, timely, secure, or error-free</li>
                  <li>Warranties regarding the accuracy, reliability, or quality of generated names</li>
                  <li>Warranties that generated names are available for use or registration</li>
                  <li>Warranties that generated names do not infringe on third-party rights</li>
                </ul>
                <p className="text-muted-foreground">
                  You expressly understand and agree that your use of the service is at your sole risk.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">6. Limitation of Liability</h2>
                <p className="text-muted-foreground mb-4">
                  To the fullest extent permitted by applicable law, Name Finder shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
                </p>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Your use or inability to use the service</li>
                  <li>Any unauthorized access to or use of our servers</li>
                  <li>Any bugs, viruses, or other harmful code transmitted to or through our service</li>
                  <li>Any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content</li>
                  <li>Trademark or copyright disputes arising from your use of generated names</li>
                  <li>Domain registration issues or costs</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">7. Third-Party Links and Services</h2>
                <p className="text-muted-foreground mb-4">
                  Our Site may contain links to third-party websites or services (such as domain registrars) that are not owned or controlled by Name Finder.
                </p>
                <p className="text-muted-foreground mb-4">
                  Name Finder has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit.
                </p>
                <p className="text-muted-foreground">
                  <strong>Affiliate Disclosure:</strong> We may earn commissions from purchases made through affiliate links to domain registrars. This does not affect the price you pay.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">8. Advertising</h2>
                <p className="text-muted-foreground">
                  Our Site displays advertisements through Google AdSense. These advertisements are served by Google and may be personalized based on your browsing history. We do not control the content of advertisements displayed on our Site.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">9. Modifications to Service</h2>
                <p className="text-muted-foreground">
                  Name Finder reserves the right to modify, suspend, or discontinue the service (or any part thereof) at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">10. Governing Law</h2>
                <p className="text-muted-foreground">
                  These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Name Finder operates, without regard to its conflict of law provisions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">11. Changes to Terms</h2>
                <p className="text-muted-foreground">
                  We reserve the right to update or modify these Terms & Conditions at any time without prior notice. Your continued use of the Site after any changes constitutes acceptance of those changes.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">12. Contact Information</h2>
                <p className="text-muted-foreground mb-4">
                  If you have any questions about these Terms & Conditions, please contact us:
                </p>
                <ul className="list-none space-y-2 text-muted-foreground">
                  <li>Email: contact@namefinder.com</li>
                  <li>Website: <a href="https://namefinder-nu.vercel.app" className="text-primary hover:underline">namefinder-nu.vercel.app</a></li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">13. Severability</h2>
                <p className="text-muted-foreground">
                  If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms will otherwise remain in full force and effect.
                </p>
              </section>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Terms;
